#!/usr/bin/env bash
set -eu

git push origin master
(git branch -D gh-pages || echo "no gh-pages branch to delete: passing")
git checkout -b gh-pages
npm run build
git add thumbnails -f
git commit -m 'update build'
git push origin --force gh-pages
git checkout master
